### ISSUE TITLE
Cant get the status and progress reporting to work

### ISSUE THREAD

**Issue by kramerdog** [inkstak/activejob-status#13]
My code within my controller looks like this:

```
   include ActiveJob::Status

    job = MyJob.perform_later(response[:access_token])

    status = ActiveJob::Status.get(job.job_id)

    # Need to work out if the job has finished
    while !status.completed? do
      sleep(10)
      status = ActiveJob::Status.get(job.job_id)
      debug('status', status)
      debug('completed', status.completed?)
      debug('progress', status.progress)
    end
```

which gives:

```
** status = --- !ruby/object:ActiveJob::Status::Status
job: b6422d6f-7c98-400e-a709-9718443ce1da

** completed = false
** progress = NaN
```

The status never moves to completed even when the Job has run.

Within MyJob I am doing:

```
      progress.total = source_urls.count
```

and then within my loop

```
        progress.increment

        debug('progress', progress)
```

which gives:

```
progress = --- !ruby/object:ActiveJob::Status::Progress
job: &1 !ruby/object:GeniJob
  arguments:
  - 8VkXh0ifrm4U79Se5oUTIjPWw3tVdlbieIaRcHwr
  job_id: b6422d6f-7c98-400e-a709-9718443ce1da
  queue_name: default
  priority: 
  executions: 1
  exception_executions: {}
  timezone: Brisbane
  provider_job_id: 911bd9f17d730ae61213e8b6
  serialized_arguments: 
  locale: en
  enqueued_at: '2021-03-31T01:57:34Z'
  status: !ruby/object:ActiveJob::Status::Status
    job: *1
  progress: !ruby/object:ActiveJob::Status::Progress
    job: *1
    total: 32
    progress: 31
total: 32
progress: 31
```

So you can see that the progress is incrementing within the Job but not visible to the Controller.

What am I doing wrong?
